#!/usr/bin/zsh

WEIGHTS=/run/media/juju/backup_loja/checkpoints/regular/train/yolov3.tf
WEIGHTS_TINY=/run/media/juju/backup_loja/checkpoints/tiny/train/yolov3-tiny.tf

FACE_SET=FaceDetection
FACE_SET_FOLDER=/run/media/juju/backup_loja

CHECKPOINTS_FOLDER=/run/media/juju/backup_loja/checkpoints
EPOCHS=80
BATCH_SIZE=16

eval "$(conda shell.zsh hook)"
conda activate yolov3-tf2-gpu

while [ $# -gt 0 ]; do
    key=$1

    case $key in
        -h|--help)
            echo "convenience script for training yolo versions"
            echo "available options are:"
            echo "    -h|--help: show this help message"
            echo "    --person-set: name of the person set, defaults to $PERSON_SET"
            echo "    --face-set: number of the face set, defaults to $FACE_SET"
            echo "    --checkpoints-folder: checkpoints root folder, defaults $CHECKPOINTS_FOLDER"
            echo "    --epochs: number of epochs to train, defaults to $EPOCHS"
            echo "    --batch-size: batch size, defaults to $BATCH_SIZE"
            exit
        ;;

        --person-set)
            PERSON_SET=$2
            shift
            shift
        ;;

        --face-set)
            FACE_SET=$2
            shift
            shift
        ;;

        --checkpoints-folder)
            CHECKPOINTS_FOLDER=$2
            shift
            shift
        ;;

        --epochs)
            EPOCHS=$2
            shift
            shift
        ;;

        --batch-size)
            BATCH_SIZE=$2
            shift
            shift
        ;;
    esac
done

# face detector
FACE_TRAIN_RECORD=${FACE_SET_FOLDER}/${FACE_SET}_train.tfrecord
FACE_VAL_RECORD=${FACE_SET_FOLDER}/${FACE_SET}_val.tfrecord
FACE_TRAIN_DATA=${FACEOT_FOLDER}/${FACE_SET}/train
FACE_TRAIN_LABELS=${FACEOT_FOLDER}/${FACE_SET}/train
FACE_VAL_DATA=${FACEOT_FOLDER}/${FACE_SET}/val
FACE_VAL_LABELS=${FACEOT_FOLDER}/${FACE_SET}/val

python tools/converter.py                    \
    --classes ./data/face-det.names          \
    --output_train_file ${FACE_TRAIN_RECORD} \
    --output_val_file ${FACE_VAL_RECORD}     \
    --train_data_dir ${FACE_TRAIN_DATA}      \
    --train_labels_dir ${FACE_TRAIN_LABELS}  \
    --val_data_dir ${FACE_VAL_DATA}          \
    --val_labels_dir ${FACE_VAL_LABELS}

python train.py                                    \
    --dataset ${FACE_TRAIN_RECORD}                 \
    --val_dataset ${FACE_VAL_RECORD}               \
    --classes ./data/face-det.names                \
    --num_classes 1                                \
    --mode fit --transfer darknet                  \
    --batch_size ${BATCH_SIZE}                     \
    --epochs ${EPOCHS}                             \
    --weights ${WEIGHTS}                           \
    --checkpoints ${CHECKPOINTS_FOLDER}/face/train \
    --weights_num_classes 80

python train.py                                         \
    --dataset ${FACE_TRAIN_RECORD}                      \
    --val_dataset ${FACE_VAL_RECORD}                    \
    --classes ./data/face-det.names                     \
    --num_classes 1                                     \
    --mode fit --transfer darknet                       \
    --batch_size ${BATCH_SIZE}                          \
    --epochs ${EPOCHS}                                  \
    --weights ${WEIGHTS_TINY}                           \
    --checkpoints ${CHECKPOINTS_FOLDER}/face-tiny/train \
    --weights_num_classes 80                            \
    --tiny
